name: Swift Test and Build

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create screenshots
        run: fastlane screenshots
      - name: Run tests
        run: fastlane tests
